# Generated by Django 5.0.3 on 2024-03-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Juego',
            new_name='Jugadores',
        ),
    ]
