# Generated by Django 5.0.3 on 2024-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_rename_juego_jugadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugadores',
            options={'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RenameField(
            model_name='jugadores',
            old_name='rol',
            new_name='activa',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='nivel',
            field=models.CharField(choices=[('AMATEUR', 'Amateur'), ('NORMAL', 'Normal'), ('EXPERT', 'Expert')], default='AMATEUR', max_length=7),
        ),
    ]
