# Generated by Django 5.0.3 on 2024-03-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
        ('jugadores', '0003_alter_jugadores_options_rename_rol_jugadores_activa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='juego',
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.jugadores')),
            ],
        ),
    ]
