# Generated by Django 5.0.3 on 2024-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_remove_jugadores_juego_participaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participaciones',
            options={'verbose_name_plural': 'Participaciones'},
        ),
        migrations.AddField(
            model_name='participaciones',
            name='detalles',
            field=models.JSONField(default=dict),
        ),
    ]
