# Generated by Django 5.0.3 on 2024-03-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_participaciones_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participaciones',
            name='detalles',
        ),
    ]
