# Generated by Django 5.0.3 on 2024-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0006_remove_participaciones_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='participaciones',
            name='detalles',
            field=models.JSONField(null=True),
        ),
    ]
