# Generated by Django 5.0.3 on 2024-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0007_participaciones_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='contrasenia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
