# Generated by Django 5.0.3 on 2024-03-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0008_jugadores_contrasenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='contrasenia',
        ),
    ]
