# Generated by Django 5.0.3 on 2024-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0009_remove_jugadores_contrasenia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='nombre',
            new_name='password',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='usuario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='fecha_de_alta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
