# Generated by Django 5.0.3 on 2024-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0010_rename_nombre_jugadores_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
