# Generated by Django 5.0.3 on 2024-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0011_jugadores_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
