# Generated by Django 5.0.3 on 2024-04-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0014_alter_jugadores_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
