# Generated by Django 5.0.3 on 2024-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0015_alter_jugadores_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='administrador',
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
