# Generated by Django 5.0.3 on 2024-04-02 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0017_alter_jugadores_fecha_de_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='fecha_de_alta',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='fecha_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='password',
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
