# Generated by Django 5.0.3 on 2024-03-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='nombre_corto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
